nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

database:
  batch:
    name: hmpps_court_case_service_db
    endpoint: localhost:5432
    username: admin
    password: password
#  source: # dev
#    name: dbaaade99b4f658d25
#    endpoint: localhost:5430
#    username: cp0Okg8u16
#    password: Rpymb3UG2DA7D3NZ
  source: # preprod
    name: db561e0a5371686304
    endpoint: localhost:5431
    username: cpMhnJcXxW
    password: oH54rNPdgLcLvRYy
  target:
    name: hmpps_court_case_service_db
    endpoint: localhost:5432
    username: admin
    password: password

spring:
  datasource:
    url: jdbc:postgresql://${database.batch.endpoint}/${database.batch.name}?currentSchema=${database.batch.schema}
    username: ${database.batch.username}
    password: ${database.batch.password}
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

app:
  datasource:
    source:
      url: jdbc:postgresql://${database.source.endpoint}/${database.source.name}?schema=${database.source.schema}
      username: ${database.source.username}
      password: ${database.source.password}
    target:
      url: jdbc:postgresql://${database.target.endpoint}/${database.target.name}?schema=${database.target.schema}
      username: ${database.target.username}
      password: ${database.target.password}
