package uk.gov.justice.digital.hmpps.courtcasedatamigrationservice.domain.source

import java.math.BigDecimal
import java.sql.Timestamp

data class OffenceQueryResult(
  val id: Int,
  val fkHearingDefendantId: Long,
  val offenceCode: String?,
  val summary: String,
  val title: String,
  val sequence: Int,
  val act: String?,
  val listNo: Int?,
  val shortTermCustodyPredictorScore: BigDecimal?,
  val created: Timestamp?,
  val createdBy: String?,
  val lastUpdated: Timestamp?,
  val lastUpdatedBy: String?,
  val deleted: Boolean?,
  val version: Int?,
  val pleaId: Int?,
  val pleaDate: Timestamp?,
  val pleaValue: String?,
  val pleaCreated: Timestamp?,
  val pleaCreatedBy: String?,
  val pleaLastUpdated: Timestamp?,
  val pleaLastUpdatedBy: String?,
  val pleaDeleted: Boolean?,
  val pleaVersion: Int?,
  val verdictId: Int?,
  val verdictDate: Timestamp?,
  val verdictTypeDescription: String?,
  val verdictCreated: Timestamp?,
  val verdictCreatedBy: String?,
  val verdictLastUpdated: Timestamp?,
  val verdictLastUpdatedBy: String?,
  val verdictDeleted: Boolean?,
  val verdictVersion: Int?,
  val judicialResults: String?,
)
