package uk.gov.justice.digital.hmpps.courtcasedatamigrationservice.domain

enum class SyncJobType {
  OFFENDER_ID_DEFENDANT,
  OFFENDER_ID_OFFENDER_MATCH,
  DEFENDANT_ID_DEFENDANT_OFFENCE,
  OFFENCE_ID_DEFENDANT_OFFENCE,
  DEFENDANT_ID_OFFENDER_MATCH_GROUP,
  OFFENDER_MATCH_GROUP_ID_OFFENDER_MATCH,
  PROSECUTION_CASE_ID_OFFENDER_MATCH_GROUP,
  DEFENDANT_ID_CASE_COMMENT,
  CASE_ID_CASE_COMMENT,
}
