CREATE SEQUENCE hmpps_court_case_batch_metadata.BATCH_JOB_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE hmpps_court_case_batch_metadata.BATCH_JOB_EXECUTION_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE hmpps_court_case_batch_metadata.BATCH_STEP_EXECUTION_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE hmpps_court_case_batch_metadata.BATCH_JOB_EXECUTION_CONTEXT_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE hmpps_court_case_batch_metadata.BATCH_STEP_EXECUTION_CONTEXT_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
