INSERT INTO hmpps_court_case_batch_metadata.HMPPS_BATCH_SCHEDULING_CONFIG (ID, JOB_NAME, IS_ENABLED) VALUES (3, 'HEARING', FALSE);
INSERT INTO hmpps_court_case_batch_metadata.HMPPS_BATCH_SCHEDULING_CONFIG (ID, JOB_NAME, IS_ENABLED) VALUES (4, 'CASE', FALSE);
INSERT INTO hmpps_court_case_batch_metadata.HMPPS_BATCH_SCHEDULING_CONFIG (ID, JOB_NAME, IS_ENABLED) VALUES (5, 'DEFENDANT_OFFENCE', FALSE);