INSERT INTO hmpps_court_case_batch_metadata.HMPPS_BATCH_SCHEDULING_CONFIG (ID, JOB_NAME, IS_ENABLED) VALUES (10, 'CASE_COMMENT', FALSE);
INSERT INTO hmpps_court_case_batch_metadata.HMPPS_BATCH_SCHEDULING_CONFIG (ID, JOB_NAME, IS_ENABLED) VALUES (11, 'OFFENDER_ID_DEFENDANT', FALSE);
INSERT INTO hmpps_court_case_batch_metadata.HMPPS_BATCH_SCHEDULING_CONFIG (ID, JOB_NAME, IS_ENABLED) VALUES (12, 'OFFENDER_ID_OFFENDER_MATCH', FALSE);
INSERT INTO hmpps_court_case_batch_metadata.HMPPS_BATCH_SCHEDULING_CONFIG (ID, JOB_NAME, IS_ENABLED) VALUES (13, 'DEFENDANT_ID_DEFENDANT_OFFENCE', FALSE);
INSERT INTO hmpps_court_case_batch_metadata.HMPPS_BATCH_SCHEDULING_CONFIG (ID, JOB_NAME, IS_ENABLED) VALUES (14, 'OFFENCE_ID_DEFENDANT_OFFENCE', FALSE);
INSERT INTO hmpps_court_case_batch_metadata.HMPPS_BATCH_SCHEDULING_CONFIG (ID, JOB_NAME, IS_ENABLED) VALUES (15, 'DEFENDANT_ID_OFFENDER_MATCH_GROUP', FALSE);
INSERT INTO hmpps_court_case_batch_metadata.HMPPS_BATCH_SCHEDULING_CONFIG (ID, JOB_NAME, IS_ENABLED) VALUES (16, 'OFFENDER_MATCH_GROUP_ID_OFFENDER_MATCH', FALSE);
INSERT INTO hmpps_court_case_batch_metadata.HMPPS_BATCH_SCHEDULING_CONFIG (ID, JOB_NAME, IS_ENABLED) VALUES (17, 'PROSECUTION_CASE_ID_OFFENDER_MATCH_GROUP', FALSE);